[package]
name = "test"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]

#[[bin]]
#name = "server"
#path = "src/server.rs"
#
#[[bin]]
#name = "client"

[dependencies]
mio = "0.5.0"
bytes = "0.3.0"
slab = "0.1.0"